### ISSUE TITLE
Не отображаются иконки, если директория не manager

### ISSUE THREAD

**Issue by krava77** [CrazyBoy49z/iconTV#16]
### Резюме

О чем эта проблема.

### Шаг для воспроизведения

Как воспроизвести проблему?

### Наблюдаемое поведение

Как она себя вела после следующих шагов выше.

### Ожидаемое поведение

Как это должно вести себя после следующих шагов выше.

### Среда

Версия IconTV, версия MODX, браузер и т.д.

**Comment by krava77** [comment]
Здравствуйте,
Не отображаются иконки, если переименовать менеджер в директорию, отличную от "manager". Ошибка в файле **icontv.class.php**, строка **170**
> \core\components\icontv\model\icontv\icontv.class.php

Было бы не плохо исправить на следующий код `$baseCSS = MODX_MANAGER_PATH . '/templates/default/css/index.css';`

Благодарю за проделанную работу 👍

**Comment by CrazyBoy49z** [comment]
Извините за ошибку. Спасибо за замечание. Сегодня сделаю обновление, с данным исправлением

**Comment by CrazyBoy49z** [comment]
Извините не успел раньше исправить
