### ISSUE TITLE
При создании нового шаблона не рендириться поле "Значок" iconTV

### ISSUE THREAD

**Issue by OlegShchavelev** [CrazyBoy49z/iconTV#19]
## Сообщение об ошибке

При заведении нового шаблона. Не посходит рендер поля "Значок"

### Шаг для воспроизведения

Создать новый шаблон. 

![изображение](https://user-images.githubusercontent.com/20732384/98623970-d8028680-231d-11eb-9138-3928c13cba63.png)

После сохранения шаблона, рендеринг так же не происходит.

![изображение](https://user-images.githubusercontent.com/20732384/98624088-17c96e00-231e-11eb-9571-f1e499b1d042.png)

Открыл шаблон через CMS. И почистил кэш в браузере (Без этого так же рендеринг не происходит).

![изображение](https://user-images.githubusercontent.com/20732384/98624222-637c1780-231e-11eb-891e-f9754aec4aee.png)

Версия IconTV, версия MODX, браузер и т.д.

IconTV 1.3.6-beta MODX 2.8.1 браузер Firefox 82.0.2 (64-битный) PHP 7.4 MYSQL 5.7

**Comment by OlegShchavelev** [comment]
Юр, о хорошо что сразу issue пошел писать. Создаю следующий шаблон после того как проделал все эти процедуры.

![изображение](https://user-images.githubusercontent.com/20732384/98624688-61ff1f00-231f-11eb-8095-09e51cdc7c25.png)

Ну что хочется отметить что данный шаблон я создавал через пункт контекстного меню. Так как данный шаблон мне нужно положить в определенную категорию (modCategory)

**Comment by CrazyBoy49z** [comment]
Исправлено в версии 1.3.10
