### ISSUE TITLE
Не получается выбрать никакой из значков вообще.

### ISSUE THREAD

**Issue by bndch** [CrazyBoy49z/iconTV#21]
Не успел толком попользоваться icontv, как вдруг он запретил мне использовать любые значки.
Удалить не получается, так как слетают все настройки и "шаблоны" тупо не открываются выдавая ошибку.
https://monosnap.com/file/k1uvvqpUmEnmTEhHxWEoh6uvQm2elg

**Comment by CrazyBoy49z** [comment]
Здравствуйте, мои контакты на главной в гите, напишите в личку. Скорее конфликт с каким то плагином

**Comment by CrazyBoy49z** [comment]
Закрыто через отсутствие ответа
