### ISSUE TITLE
Добавления дополнительных шрифтовых иконок 

### ISSUE THREAD

**Issue by OlegShchavelev** [CrazyBoy49z/iconTV#8]
На текущий момент тип поле iconTV, реализован выбор библиотеки:

- FontAwesomev 5
- FontAwesome v4.3.0
- FontAwesomev4.7.0 

Реализовать механизм добавления сторонних шрифтовых библиотек. Сергей задал вопрос по библиотеке https://iconify.design/icon-sets/simple-line-icons 

В зависимости от методологии верстки проекта, выбор библиотек шрифтовых иконок может быть различным. К примеру кто верстает на UIkit, имеет возможность использовать свою библиотеку из [фраймворка](https://getuikit.com/v2/docs/icon.html). 

Скажем так все очень индивидуально.

**Comment by Sentinel-7** [comment]
Можно наверное все сделать через системную настройку, к примеру через запятую вставлять пути к файлам иконок cdn и так же названия

**Comment by CrazyBoy49z** [comment]
> Реализовать механизм добавления сторонних шрифтовых библиотек. Сергей задал вопрос по библиотеке https://iconify.design/icon-sets/simple-line-icons

Посмотрел, добавлю возможность загрузки скриптов, дополнительные шрифты #3

> В зависимости от методологии верстки проекта, выбор библиотек шрифтовых иконок может быть различным. К примеру кто верстает на UIkit, имеет возможность использовать свою библиотеку из [фраймворка](https://getuikit.com/v2/docs/icon.html).

Здесь проблем нет, только нужно собрать массив данных [здесь ](https://github.com/CrazyBoy49z/iconTV/tree/master/core/components/icontv/elements/config). Так что буду рад PR

**Comment by Sentinel-7** [comment]
> только нужно собрать массив данных здесь

Собрал

**Comment by CrazyBoy49z** [comment]
Спасибо
